README.md
It was: N501Y is associated with _a_ recently reported 'new variants' in the UK and South Africa:
Deleted "a"
=> Updated README.md - Fixed typo

web/src/components/ClusterButtonPanel/ClusterButton.tsx, web/src/components/ClusterButtonPanel/ClusterButtonPanel.tsx, web/src/components/Home/HomePage.tsx, web/src/components/Variants/VariantsPage.tsx, web/src/pages/variants/[clusterName].tsx, web/src/pages/variants/index.tsx
This simplifies code and fixes broken navigation to `/variant/<name>` pages
=> fix: replace handmade routing with link navigation between variant pages

web/package.json, web/src/components/Common/SharingPanel.tsx, web/src/components/Layout/Footer.tsx, web/src/constants.ts, web/yarn.lock
Resolves #22 
This adds social media sharing buttons
There is a few new constants in `src/constants`:
- `TWITTER_RELATED`: an array of twitter usernames (without `@`) which Twitter may suggest to follow to users engaged with the tweet
- `TWITTER_HASHTAGS`: hashtags to add to the tweet body
- `FACEBOOK_HASHTAG`: hashtags to add to Facebook post
https://github.com/hodcroftlab/covariants/blob/aa5373af164b8b8b17d9cb0a4709ace4cbf0fcab/web/src/constants.ts#L18-L21
=> feat: add social media sharing buttons

.all-contributorsrc, web/config/next/next.config.ts, web/config/next/withJson.ts, web/package.json, web/src/components/Common/TeamCredits.tsx, web/src/components/Common/TeamCreditsContributor.tsx, web/src/io/getContributors.ts, web/src/types/all-contributorsrc.d.ts, web/yarn.lock
This adds avatars of contributors to the footer of the app.
Uses all-contributors to automate the process.
When readme is finalized we could also add those to the readme.
The list is stored here:
https://github.com/hodcroftlab/covariants/blob/feat/contribs/.all-contributorsrc
```
npm install -g all-contributors-cli
```
```
all-contributors check
```
```
all-contributors add <github_username> <contribution1>,<contribution2>,...
```
For example:
```
all-contributors add ivan-aksamentov code,design,infra,doc
```
(in the future, the readme does not contain the contributors section yet)
```
all-contributors generate
```
List of types of contributions:
https://allcontributors.org/docs/en/emoji-key
=> Acknowledge contributors

web/src/components/Variants/VariantsPage.tsx, web/src/io/getClusterContent.ts
This turns Next.js `dynamic()` `import`s into static `require`s. This way, the markdown content on variants pages is rendered statically, and there is no blink of empty content and no page reflow when switching variants.
The variants pages should feel more responsive and seamless.
=> Avoid content blinking on variants pages

web/src/components/Common/MdxComponents.tsx, web/src/components/Common/MutationBadge.tsx, web/src/components/Common/__tests__/parseAminoacidMutation.test.ts, web/src/components/Common/__tests__/parseNucleotideMutation.test.ts, web/src/components/Common/formatMutation.ts, web/src/components/Common/parseAminoacidMutation.ts, web/src/components/Common/parseNucleotideMutation.ts, web/src/components/Variants/DefiningMutations.tsx, web/src/types.ts
This:
- adds shorter aliases for existing aminoacid and nucleotide badges (for convenience, when using in markdown)
- adds variant badges which link to variant pages
- imports these new components explicitly to markdown, so that explicit import statements are no longer needed
Examples:
```jsx
<NucMut mut="C123T" />
<AaMut mut="S:N501" />
<Var name="S:N501" />
<Var name="S:N501" href="/variant/S.N501" />
<Var name="S:N501" href="/foo/bar" />
<Var name="S:N501" href="https://example/com/foo/bar" />
```
=> Improve mutation badges

web/.eslintignore, web/config/next/lib/EmitFilePlugin.js, web/config/next/next.config.ts, web/config/next/withRobotsTxt.ts, web/infra/lambda-at-edge/basicAuth.js, web/infra/lambda-at-edge/modifyOutgoingHeaders.lambda.js, web/package.json, web/public/robots.txt
This adds:
- dynamically generated `robots.txt`
- basic auth via Lambda@Edge
=> Protect non-release deployments from web crawlers

docs/Contributing.md
Documents the need to run `cp .env.example .env` before general dev.
I'm not sure exactly how you'll want to do this, perhaps in a different "set-up" section? (Do make any edits) But I think that despite the relatively helpful error message, it would be worth documenting this need because it isn't clear exactly where the error message is being surfaced from and I initially assumed it was some unhappy node package rather than relating to this package itself.
=> Document copying .env.example

web/src/components/Variants/VariantsPage.tsx
instead of `display_name`
Otherwise you get a 404.
Tested locally
Closes #65
=> Fix Githuburl link from a variant page to point to build_name

docs/Contributing.md, web/package.json
This adds hardcoding to a path that seems to work in Windows. (See discussion in https://github.com/nextstrain/nextclade/issues/313 and https://github.com/hodcroftlab/covariants/issues/18).
It's a bit hacky, I don't have a good understanding of structuring node commands. Improvements welcome.
=> Add basic windows dev support

web/src/components/CountryDistribution/CountryDistributionPlot.tsx, web/src/components/CountryDistribution/CountryDistributionPlotTooltip.tsx
Resolves #72 
Adds 2 rows:
- "total" number of sequences at the bottom
- "others" as a difference of total and sum of number of sequences for all variants (variants which are not filtered out with checkboxes)
Related: #76
=> feat: add 'total' and 'others' to per-country plot tooltips

web/src/components/CountryDistribution/CountryDistributionPlot.tsx, web/src/components/CountryDistribution/CountryDistributionPlotTooltip.tsx
Extends and depends on #75
Note: This PR is done, but is marked as draft, to avoid out-of order merges, because it requires #75 to be merged first. Safe to unmark (click "Ready for review") and merge when #75  is on master.
This adds another column "Freq", which value is `number_of_sequences / total_sequences`
=> feat: add frequency column for per-country plot tooltips

content/PerCountryIntro.md, web/src/components/CountryDistribution/CountryDistributionPlot.tsx, web/src/io/getClusters.ts, web/src/theme.ts
Resolves #85
This adds fill color to "others" entry on the per-country plots. The color is reused in the plot tooltip, to fill the rectangle near the "others" entry as well.
The color can be adjusted here: 
https://github.com/hodcroftlab/covariants/blob/2f6483d978a500f8302bdd55a9a1758252a69a66/web/src/theme.ts#L149
=> feat: add color to "others" variant on per-country plots

web/src/components/Link/LinkExternal.tsx
The external-link icon conventionally appears *after* the link text (e.g, see [these](https://en.wikipedia.org/wiki/COVID-19_pandemic#References), [examples](https://designnotes.blog.gov.uk/2016/11/28/removing-the-external-link-icon-from-gov-uk/)).
Covariants.org currently places the icons *before* the link text, which looks unusual; this PR reverses this.
=> place external-link icon after link

web/src/components/ClusterDistribution/ClusterDistributionPage.tsx, web/src/components/CountryDistribution/CountryDistributionPage.tsx, web/src/components/DistributionSidebar/ClusterFilters.tsx, web/src/components/DistributionSidebar/CountryFilters.tsx, web/src/components/DistributionSidebar/DistributionSidebar.tsx
Resolves #96
Adds "Select all" and "Deselect all" links to the filtering sidebar panels, which allow toggling all countries or variants
=> feat: add ability to select and deselect all country or variant filters

web/src/styles/global.scss
Currently the links to specific nextstrain builds look like two links, because the names formatted with `<code>` are in black rather than blue:
Currently:
After this PR:
=> color code in link to match rest of link

content/Home.md, web/src/components/Common/MutationBadge.tsx, web/src/components/Common/__tests__/parseVariant.test.ts, web/src/components/Common/formatMutation.ts, web/src/components/Common/parseVariant.ts, web/src/components/Variants/DefiningMutations.tsx, web/src/types.ts
This:
- makes sure that badges for variants "20E (EU1)" and "20A.EU2" are rendered correctly
- adds unit tests for variant string parser for some of the variants
=> Ensure variant badges work for named variants

web/src/components/Variants/VariantsPage.tsx, web/src/io/getClusters.ts
If a cluster entry in `clusters.py` does not have a `nextstrain_url` field, then Nextstrain link will not be shown on cluster's page. The text "No dedicated Nextstrain build is available" will be show instead.
Resolves #119
=> Allow clusters to not have a nextstrain link

content/clusters/20A.EU1.md
Believe this should read 'N-terminal domain' (pertaining to the 'N-terminus') instead of 'non-terminal domain'.
=> Fix typo in 20A.EU1.md

scripts/convert_to_web_app_json.py, web/src/components/Acknowledgements/AcknowledgementsPage.tsx, web/src/io/getClusterEpiIslsNumChunks.ts
This PR
- Adds warning messages if acknowledgements data is missing when running web data update script. The script now checks for:
- `acknowledgements_keys.json` to contain all clusters present in `clusters.json` (that are not of `type: do_not_display`)
- presence of acknowledgements directory (with JSON chunks) for each cluster
- number and names of chunk files consistency with `numChunks` in `acknowledgements_keys.json` for each cluster
- Prevents "Acknowledgements" page from crashing the whole application when acknowledgements data is incomplete (by filtering clusters displayed on "Acknowledgements" to the ones present in `acknowledgements_keys.json`)
=> Warn about missing acknowledgements on data update

scripts/allClusterDynamics_faster.py, scripts/clusters.py
Currently CoVariants.org uses `sequence-diagnostics_gisaid.tsv` - as this is being phased out of the `ncov` workflow, this PR switches to using `mutation_summary_gisaid.tsv` which contains much of the same information (though slightly differently represented in some cases).
In future, using this file will allow specification of the exact mutation one wants to select, rather than just 'any mutation at this nucleotide position', and also in theory to use AA mutations. However, importantly, if there's some kind of frameshift that impacts translation, then AA mutations may not show up, whereas nucleotide mutations always appear.
This is why I'm sticking to using nucleotide mutations for the foreseeable future.
As part of this PR - since `mutation_summary` is 1-based, whereas …
=> Switch to using `mutation_summary` file

scripts/name_table.py, web/data/nameTable.json, web/src/components/Common/NameTable.tsx, web/src/io/getNameTable.ts
This adds the new [Greek letter variant names](https://www.who.int/en/activities/tracking-SARS-CoV-2-variants/) to the table of variants:
=> add new WHO Labels to variant table

web/package.json, web/src/components/ClusterButtonPanel/ClusterButton.tsx, web/src/components/Common/NameTable.tsx, web/src/components/CountryDistribution/CountryDistributionPlotTooltip.tsx, web/src/components/DistributionSidebar/ClusterFilters.tsx, web/src/styles/_variables.scss, web/src/styles/global.scss, web/src/theme.ts, web/yarn.lock
Switched the font for variant names in some places to monospace. This way the sections in new variant names are nicely aligned.
Current font is "Source Code Pro"
We might try other, prettier fonts too. I would think that a monospace sans serif font would do the best here. Serif fonts jump out immediately, because the rest of the page is sans. Here are some random font viewers:
https://fonts.google.com/?category=Sans+Serif,Monospace
https://www.1001fonts.com/monospaced-fonts.html
https://www.fontsquirrel.com/fonts/list/classification/monospaced
https://fontsarena.com/monospace/
https://en.wikipedia.org/wiki/List_of_monospaced_typefaces
Screenshots:
---
---
---
=> Use monospace font for variants, prettify name table

content/VariantsPageIntro.md, web/src/components/ClusterButtonPanel/ClusterButton.tsx, web/src/components/ClusterButtonPanel/ClusterButtonGroup.tsx, web/src/components/ClusterButtonPanel/ClusterButtonPanel.tsx, web/src/components/ClusterButtonPanel/ClusterButtonPanelLayout.tsx, web/src/components/Common/ClusterSidebarLayout.tsx, web/src/components/Common/NameTable.tsx, web/src/components/Home/HomePage.tsx, web/src/components/Layout/Layout.tsx, web/src/components/Variants/DefiningMutations.tsx, web/src/components/Variants/VariantsPage.tsx, web/src/components/Variants/VariantsPageIndex.tsx
This makes button sidebar width fixed, such that it is easier to find an appropriate width for all screen sizes. The layout of variants and home pages had to be revamped for that.
Now only the central text content section is responsible. Both sidebars are of fixed width. 
For smaller screens we tweak the button width slightly, along with height and font size.
=> Make cluster button sidebar width fixed

web/.browserslistrc, web/src/components/ClusterButtonPanel/ClusterButtonPanelLayout.tsx
Splitting the `flex-basis` out of the `flex` statement seems to be working correctly on Safari 14, while the compound variant does not.
Hello, Apple, anybody home?
Before:
After:
iPhone 7 iOS 12 looks fine:
=> fix: safari cluster buttons misaligned

scripts/allClusterDynamics_faster.py
Speed and logic improvements to the code
- Removes 'bad sequences' more efficiently at start
- Removes duplication of trying to remove sequences with invalid dates & bad sequences twice
- Filter mutations file to match metadata, so if a sequence has been removed from meta, it is also out of the mutations file
- (most significant) Reduces time to search for matching sequences in the mutations file
- (Unrelated) Clears some warnings associated with setting to copies of slices of dataframes
=> improve speed of some of the steps

scripts/allClusterDynamics_faster.py
Small but important change means that we filter the `metadata` contents to only use what we have a matching `mutation_summary` entry for. Until now, if the code was run on a `metadata` file which had more entries than a `mutation_summary` file (ex: in a currently going run, where `mutation_summary` hasn't been generated yet), then there will be many recent sequences which are classed as 'other' just because there's no mutation information to identify them as variants. 
However, waiting to run analyses until files were in sync often meant that it was harder to run things as often.
With this change, only sequences which have a `mutation_summary` entry are included in the analysis, so that there's less need to be so careful to ensure files are 'in sync' before running.
As an added bonus, …
=> Filter Metadata to What's in Mutation Summary before analysis

web/package.json, web/src/pages/_app.tsx, web/yarn.lock
Plot rendering depends on ResizeObserver. Older Safari don't have ResizeObserver support and crash when navigating to one of the pages containing plots.
This PR adds a global polyfill (`resize-observer-polyfill` package)  so that Safari display plot pages correctly.
Just tested this PR on Browserstack. Looks like it now works on things as far back as iPhone 6, iOS 11, circa 2014. A blast from the past!
=> Fix crash in old safari on missing ResizeObserver

web/package.json, web/src/components/CountryDistribution/CountryDistributionPlot.tsx, web/yarn.lock
Resolves #188
After #186 the cursor line became invisible because area segments on the plot are opaque:
This PR renders the `<Tooltip/>` components (which includes the cursor line) above area segments.
There is a new problem though. The "active circles" (the circles showing the value on the intersection of cursor line and area segment) are now partially obscured by area segments:
This is due to them being rendered intertwined along with area segments, so that the previous circle is obscured by the next segment:
(note `area` and `active-dot` element ordering)
I am not sure we will be able to fix that easily.
=> Render plot cursor above area segments on country plots

content/PerCountryIntro/Switzerland.md, content/RegionBreakdownInfo.md, content/clusters/21A.Delta.md
Primarily adds new links to new focal builds (Swiss-Delta + Delta+417N), but also adds a couple of other links and text changes. Tested locally, looks good.
=> Update Builds Links

web/src/components/ClusterDistribution/ClusterDistributionPlotTooltip.tsx, web/src/helpers/format.ts
This fixes formatting of dates in cluster plot tooltips.
Previously it was incorrectly showing 2-week intervals for each data point. However, the correct interval is 1 week.
This is only a visual fix, the underlying data is the same.
=> fix: format date ranges in cluster plot tooltips weekly

scripts/name_table.py, web/data/nameTable.json, web/src/components/Common/NameTable.tsx, web/src/io/getNameTable.ts
In response to the fact that the name table is squashed on mobile devices, removed "Old CoVariants Name" from the table, and shortened "other names" to "other".
This is a trade-off - right now it's unlikely anyone is still using the old CoVariants names, but in future if clades are given "official" names, then this may be useful again. However, it's likely not being widely used, and having the table be readable on mobile devices is likely more important. 
Still squashed on older devices (iPhone 5) with smaller screens, but should look good on the majority of more modern, slightly larger screens.
=> Remove old names from table

web/src/components/Common/CountryFlag.tsx
This adds a couple of country codes to the list of replacements, so that the flags are looked up correctly.
The incorrect lookup is due to us using country names which are not compliant with the ISO standard.
=> fix: add missing flags

scripts/name_table.py, web/src/components/Common/MutationBadge.tsx
Tweak to `update_name_table()` to add a bit more checking for changes in global report page availability.  General notes below.
This report linked in the name table does not exist:
- https://cov-lineages.org/global_report_B.1.617.1.html
As of now, the following pango global report pages exist:
- https://cov-lineages.org/global_report_A.23.1.html
- https://cov-lineages.org/global_report_B.1.1.529.html
- https://cov-lineages.org/global_report_B.1.1.7.html
- https://cov-lineages.org/global_report_B.1.351.html
- https://cov-lineages.org/global_report_B.1.525.html
- https://cov-lineages.org/global_report_B.1.617.2.html
- https://cov-lineages.org/global_report_P.1.html
Global reports for lineages not of VOC status were deprecated in https://github.com/cov-lineages/lineages-website/commit/ddd6db7 …
=> name_table.py, MutationBadge.tsx: repair global reports polling and display logic

docs/Contributing.md, web/src/components/Variants/ProteinCard.tsx
Updating references to the protein images directory to match the new location following https://github.com/hodcroftlab/covariants/pull/172
`content/clusters/proteins/` -> `web/public/proteins/gif`
=> Update references to the protein images directory

web/src/components/ClusterDistribution/ClusterDistributionPage.tsx, web/src/components/Layout/Layout.tsx
Just a little idea to keep the tooltip settings in view when scrolling through the charts :)
The removal of the overflow is a risky one though, hopefully it doesn't break anything 🤞🏽
=> Make tooltip settings sticky

web/src/components/Common/CountryFlag.tsx
Adds country names that do not adhere to ISO standards to the list of workarounds in order to be able to display flags.
=> feat: add missing flags

web/src/components/Variants/CladeSchema.tsx
Just adjusts the wording underneath the clade figure slightly.
@ivan-aksamentov I wanted to also add a link to https://github.com/nextstrain/ncov-clades-schema in there, probably around "Nextstrain clades" - so people can fully see where the figure comes from - but I couldn't figure out how to get in-text links working in the TSX file.
No worries if this is a thing that's a pain, we can live without - was just thinking might be helpful for others who might want to use the figure!
=> Adjust wording on clade figure slightly

scripts/allClusterDynamics_faster.py
Implement pandas read_csv parameter `usecols` to only read selected columns from metadata in order to speed up the script and reduce memory usage.
TODO:
=> implement usecols

web/package.json, web/yarn.lock
This forcefully downgrades  `ts-toolbelt`  package, because of its incompatibility with `merge-anything` package (introduced in https://github.com/hodcroftlab/covariants/pull/279)
See: https://github.com/mesqueeb/merge-anything/pull/16
=> chore(web): fix web build

web/src/components/DistributionSidebar/DistributionSidebar.tsx, web/src/io/getPerCountryData.ts
This removes sorting of cluster state for "per country" page introduced in https://github.com/hodcroftlab/covariants/pull/279
This ensures the old ordering of colored areas on area plots.
A complication of that removal is that sidebar component requires sorted clusters. However without it being sorted globally in case of "per country" page, it comes unsorted into the component. So sidebar now additionally performs the sorting.
Without sorting:
With sorting:
=> fix: don't sort clusters for "per country" plots

web/src/components/Common/CountryFlag.tsx
This adds a few country names to the exceptions list, in order for flags to be rendered correctly.
This is due to inconsistent naming we use, which is not compliant with ISO-3166-1 Alpha-2 Code and with the the flag library we are using.
=> fix(web): add missing country flags

web/src/seo/seoMetadata.ts
As raised in #288 - not all pages have updating titles or descriptions.
This is a quick manual update so that we have some more specific details for each page. (I scripted the part with the variants/mutations.) 
@ivan-aksamentov , are there restrictions on what symbols can be used in these headers/descriptions? I used the `build_name` object from `clusters.py` - so it might have things like spaces and parenthesis. I think this should be fine, but if you could eyeball it quickly, that would be good!
Also, I left out the `image` variable for the other pages as we don't have specific images - is that the right way to do that?
=> Update SEO metadata

web/src/components/Variants/VariantTitle.tsx
This hides the "also known as" text in the variant title if there is no alternative name.
How it is right now:
=> Hide "also known as" if no alt display name exists

scripts/include_case_counts.py, web/data/perCountryDataCaseCounts.json, web/src/components/Cases/CasesPlot.tsx
Adding a new category, currently called `Unknown`, to cases data which contains all remaining case counts that are not covered by known clades.
=> add category unknown to case count data

web/src/components/Cases/CasesPage.tsx, web/src/pages/_app.tsx, web/src/state/ClustersForCaseData.ts, web/src/state/PlacesForCaseData.ts
Resolves #299 
The URL parameters were not applied on app initialization to the recoil atoms which store the state for countries, continents and clusters specific to 'Cases' page.
This PR adds the logic that applies incoming parameters to the recoil state.
=> fix: ensure url parameters correctly apply for 'Cases' page

web/src/state/ClustersForCaseData.ts
This fixes a copy-paste mistake, where 2 Recoil atoms ended up having the same key. I renamed the key for one of the atoms.
Duplicate keys could have caused app to misbehave or crash.
=> fix: avoid duplicate keys for different recoil atoms

scripts/allClusterDynamics_faster.py
First priority remains Nextstrain clade
Second priority becomes Nextstrain_pango
Third priority is SNPs
One thing to bear in mind: this only works if Nextclade pango exists already
Code may want to be refactored to allow for a special Nextclade_pango=true field
=> feat: use Nextclade_pango lineage before snps

web/config/next/next.config.ts, web/package.json, web/src/components/Cases/CasesPlot.tsx, web/src/components/ClusterDistribution/ClusterDistributionPlot.tsx, web/src/components/Common/ChartContainer.tsx, web/src/components/Common/FadeIn.tsx, web/src/components/CountryDistribution/CountryDistributionPlot.tsx, web/src/pages/_app.tsx, web/src/polyfills.ts, web/src/types/intersection-observer.d.ts, web/yarn.lock
Hey folks,
I tried working with ECharts but I don't like it much. The scrolling issue we spoke about notwithstanding, the API is not great IMO and notice how the cursor line is not visible because reasons? I also noticed that it didn't improve performance when resizing the page and waiting for all the charts to update.
I noticed you've been trying out limiting the initial charts but I'd like to throw my hat in the ring with this. Think it's possible to extend the margin so that e.g. the chart you're about to scroll to is already rendered, but I've smoothed it out with fading anyway.
If you're keen to remove Recharts I think this would still be a useful approach. My variant chart changes are going well with Recharts though, so I can promise to implement the "brush" zooming we had on the …
=> Use intersection observer to render visible charts

scripts/cluster_analysis.py
For a given cluster, it is currently possible that both pango lineages and snps could be used to assign sequences to it. With this change, only one of these methods will be used for each cluster:
- Does this cluster have a `display_name` that is found in the metadata "Nextstrain_clade" column? -> use Nextstrain_clade
if not:
- Does this cluster have `use_pango=True` enabled? -> use pango lineages
if not:
- Does this cluster have a non-empty `snps` entry? -> use snps
if not:
- No sequence will be assigned to this cluster
Thoughts:
- Currently, no warning is printed if none of these methods are possible. Should we print a warning if this is the case or will this never happen anyway?
- The script currently only checks if `use_pango=True`, but not if the pango_lineages given in …
=> Use either pango or snps for cluster assignment, not both

.circleci/config.yml
This increases number of times AWS CLI will try the failed command again. This is especially useful for Cloudfront commands, which are (in)famous for increased failure rates.
=> chore(ci): increase retry count of aws commands on ci

scripts/clusters.py
As specified in #371 - this ensure that all `nextstrain_name` entries in `clusters.py` are in year-letter format (previously this had been inconsistent, with some being the full name and some just year-letter).
=> Change all `nextstrain_name` entries in `clusters.py` to year-letter format

web/src/io/getPerClusterData.ts, web/src/io/getPerCountryData.ts
This resolves 404 errors when fetching dynamic data from non-root pages. The fetches should always be done relative to the root `/` and not relative to the current page
=> fix(web): fetch urls relative to root, rhather than current page

web/src/state/PlacesForPerCountryData.ts
The list of `countriesToPlot.json` was mistakenly applied to regions that are not "World", this led to most of the locations not being selected for plotting by default on `/per-country` page in regions that are not "World",.
This PR fixes it by only applying the list to the "World" region only.
=> fix(web): enable all 'counties' in non-'World' region

web/src/components/Cases/CasesPlotTooltip.tsx, web/src/components/ClusterDistribution/ClusterDistributionPage.tsx, web/src/components/ClusterDistribution/ClusterDistributionPlotCard.tsx, web/src/components/CountryDistribution/CountryDistributionComponents.tsx, web/src/components/CountryDistribution/CountryDistributionPage.tsx, web/src/components/CountryDistribution/CountryDistributionPlotTooltip.tsx, web/src/components/DistributionSidebar/ClusterFilters.tsx, web/src/components/DistributionSidebar/DistributionSidebar.tsx
Resolves #505 
Behavior on hitting the pango switch:
- Cases and per-country page:
- Sidebar updates
- Tooltip updates
- Per-variant page:
- Sidebar updates
- Plot card headers update
Also changed code style such that exported component is at the top of the file.
=> feat-505: make per plotting pages respond to pango switch

web/package.json, web/src/components/CountryDistribution/CountryDistributionPage.tsx, web/src/components/SharedMutations/__tests__/mockRequests.ts, web/src/helpers/__tests__/providers.tsx, web/src/state/Places.ts, web/src/state/PlacesForCaseData.ts, web/src/state/PlacesForPerCountryData.ts, web/src/state/__tests__/Clusters.test.tsx, web/tests/home.spec.ts, web/tests/perCountry.spec.ts, web/yarn.lock
Visiting /per-country, using the country filters and then switching to a different region would leave the "country" filter for that region almost empty (see #472). 
The reason was that the default state of a country filter is taken from the url query if one is present. Using the filter in one region adds a query to the url. Switching regions updates the query but only *after* the filter state has been updated because the filter state depends directly on the selected region state. Consequently, the filter state for e.g. "Switzerland" would be taken from the previous query of e.g. "World", leaving no regions selected.
This PR fixes the bug by only setting the filter state from the url if it includes the correct region.
Bug:
[Screencast from 11.03.2025 …
=> 472 fix country filters

.github/workflows/web_staging.yml
Dependabot cannot access repo secrets and thus the deployment steps fail. [Context](https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/), [context](https://hugo.alliau.me/blog/posts/2021-05-04-migration-to-github-native-dependabot-solutions-for-auto-merge-and-action-secrets), [context](https://stackoverflow.com/questions/74957218/what-is-the-difference-between-pull-request-and-pull-request-target-event-in-git). This PR disables the deployment steps for dependabot PRs as they are not really needed.
=> fix-557: remove deployment steps for PRs triggered by dependabot

web/src/components/Cases/Cases.tsx, web/src/components/ClusterDistribution/ClusterDistribution.tsx, web/src/components/CountryDistribution/CountryDistribution.tsx, web/src/state/Clusters.ts, web/src/state/ClustersForPerCountryData.ts, web/src/state/PlacesForPerCountryData.ts
Resolves #467 
Fix: navigating on the page resets query url even though the state retains the query.
Fixed by updating url on first render of the plotting component. For the per-country page, an additional fix was needed when navigating between regions, as setting the region was scrubbing the url query.
=> 467 keep url synced with plot selection

web/src/components/Common/table/TableWithSearchPaginationFilter.tsx, web/src/components/DefiningMutations/CodingMutationsTable.tsx, web/src/components/DefiningMutations/SilentMutationsTable.tsx
-  adds the option to specify for each table, that each of the columns has the same width.
- fixes minor spelling
- makes the table "responsive" meaning, that when the minimal width (length of the title) is reached, then there appears a scroll bar at the bottom
=> feat-612: fix column width of defining mutations table

web/src/components/DefiningMutations/DefiningMutationsContent.tsx, web/src/components/DefiningMutations/DownloadDefiningMutationsButton.tsx
Adds a download button to the defining mutations page. Clicking on it, will download the available data of the selected defining mutation.
=> feat-606: add download button to defining mutations page

web/package.json, web/src/components/Cases/Cases.tsx, web/src/components/Cases/CasesComponents.tsx, web/src/components/Cases/CasesPlotCard.tsx, web/src/components/Cases/CasesPlotTooltip.tsx, web/src/components/ClusterDistribution/ClusterDistribution.tsx, web/src/components/ClusterDistribution/ClusterDistributionComponents.tsx, web/src/components/ClusterDistribution/ClusterDistributionPlotCard.tsx, web/src/components/ClusterDistribution/ClusterDistributionPlotTooltip.tsx, web/src/components/Common/PlotLayout.tsx, web/src/components/Common/table/SortingIndicator.tsx, web/src/components/Common/tooltip/Tooltip.tsx, web/src/components/Common/tooltip/TooltipTable.tsx, web/src/components/CountryDistribution/CountryDistribution.tsx, web/src/components/CountryDistribution/CountryDistributionComponents.tsx, web/src/components/CountryDistribution/CountryDistributionPlotCard.tsx, web/src/components/CountryDistribution/CountryDistributionPlotTooltip.tsx, web/src/components/DistributionSidebar/ClusterFilters.tsx, web/src/components/DistributionSidebar/CountryFilters.tsx, web/src/components/DistributionSidebar/DistributionSidebar.tsx, web/src/state/CountryStyles.ts, web/src/state/TooltipSort.ts, web/yarn.lock
Resolves #28, #367
- allows users to select the sorting direction above the plots
- uses tanstack table for sorting and filtering instead of custom solution
- slighly changes the design of the tooltip, so all three pages use the same design
=> Add tooltip sorting to cases, cluster distribution and country distribution page
